// crisis-names.js
//
// Seeded, historian-style crisis-event names. Extracted from chart-line.js so
// the production chart module exports only runtime surfaces and the test
// harness can hit this generator directly. All names are LOC keys composed via
// the i18n helper.

import { t } from "/demographics/ui/demographics-i18n.js";

/**
 * Crisis-name LOC-key pools keyed by AgeCrisisEventType. Each entry is
 * `{ names, arcs }` of `LOC_DEMOGRAPHICS_CRISIS_*` tags (composed via {@link t}):
 * `names` is the single-pick pool; `arcs` are multi-stage progressions (one
 * beat per stage). Templates that once expanded via {color}/{place}/{regional}
 * are now pre-expanded into concrete, individually localized keys. Modern age
 * has no AgeCrisis pipeline, so only Antiquity/Exploration are represented.
 * @type {Record<string, { names: string[], arcs: string[][] }>}
 */
const CRISIS_NAME_TEMPLATES = {
  ANTIQUITY_CRISIS_INVASION: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_BRONZE_AGE_COLLAPSE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_MIGRATION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_MIGRATIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_COMING_OF_THE_SEA_PEOPLES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_BARBARIAN_INVASIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_BARBARIAN_WARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_HORDE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_COMING_OF_THE_HORSE_LORDS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_MARCH_OF_STRANGERS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_DEVASTATION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_TURMOIL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_FRONTIER_COLLAPSE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_FRONTIER_WARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_NORTHERN_INVASIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_EASTERN_INVASIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_STORM_FROM_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_STORM_FROM_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_STORM_FROM_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_STORM_FROM_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_STORM_FROM_THE_HEARTLAND",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_HEARTLAND"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_BORDER_RAIDS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_BARBARIAN_INVASIONS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_FRONTIER",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_MIGRATION"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_COMING_OF_THE_HORSE_LORDS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_STORM_FROM_THE_STEPPE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_FALL_OF_THE_FRONTIER",
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_DEVASTATION"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_FRONTIER_WARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_BARBARIAN_WARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SACK_OF_THE_PROVINCES",
        "LOC_DEMOGRAPHICS_CRISIS_THE_BRONZE_AGE_COLLAPSE"
      ]
    ]
  },
  ANTIQUITY_CRISIS_PLAGUE: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_ANTONINE_PLAGUE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_GALEN",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PESTILENCE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_MORTALITY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_FEVER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PERISHING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_YEARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_DYING_TIME",
      "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_PESTILENCE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_MORTALITY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ASHES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SWEATING_SICKNESS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WASTING_PLAGUE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SUMMER_PLAGUE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WINTER_SICKNESS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SILENT_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_BLACK_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RED_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREY_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_ASHEN_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_HEARTLAND"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_SUMMER_PLAGUE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_YEARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_MORTALITY",
        "LOC_DEMOGRAPHICS_CRISIS_THE_DYING_TIME"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_SWEATING_SICKNESS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_COAST",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PESTILENCE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ASHES"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_WINTER_SICKNESS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_WASTING_PLAGUE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PERISHING",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SILENT_DEATH"
      ]
    ]
  },
  ANTIQUITY_CRISIS_LOYALTY: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_SERVILE_WARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CIVIL_WARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_REVOLT",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ANARCHY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_TURMOIL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_TYRANTS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_USURPERS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_PRETENDERS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_WARLORDS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_THIRD_CENTURY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_SUCCESSION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_LEGITIMACY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_AUTHORITY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_COLLAPSE_OF_AUTHORITY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_FRACTURING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SUNDERING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_UNREST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SOLDIER_S_REVOLT",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PRETENDERS_WAR",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WAR_OF_SUCCESSION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PROVINCIAL_REVOLTS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLT_OF_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLT_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLT_OF_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLT_OF_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLT_OF_THE_HEARTLAND"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_PRETENDERS_WAR",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CIVIL_WARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_USURPERS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_COLLAPSE_OF_AUTHORITY"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_SOLDIER_S_REVOLT",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PROVINCIAL_REVOLTS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ANARCHY",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SUNDERING"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_SUCCESSION",
        "LOC_DEMOGRAPHICS_CRISIS_THE_WAR_OF_SUCCESSION",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CIVIL_WARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_TYRANTS"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_REVOLT",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_PROVINCES",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_FRACTURING",
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_WARLORDS"
      ]
    ]
  },
  EXPLORATION_CRISIS_REVOLUTION: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_REVOLUTIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_REFORM",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLUTIONARY_YEARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_NATIONAL_REVOLUTIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SPRING_OF_NATIONS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEAR_OF_LIBERTY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEAR_OF_THE_REPUBLIC",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GLORIOUS_REVOLUTION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_AWAKENING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REFORM_MOVEMENT",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PEOPLE_S_RISING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PEOPLE_S_REVOLUTION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_NATIONAL_RISING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REPUBLICAN_RISING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_CROWN",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_REPUBLIC",
      "LOC_DEMOGRAPHICS_CRISIS_THE_FALL_OF_THE_CROWN",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CONSTITUTIONAL_CRISIS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RISINGS_IN_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RISINGS_IN_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RISINGS_IN_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RISINGS_IN_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RISINGS_IN_THE_HEARTLAND"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEAR_OF_LIBERTY",
        "LOC_DEMOGRAPHICS_CRISIS_THE_REPUBLICAN_RISING",
        "LOC_DEMOGRAPHICS_CRISIS_THE_FALL_OF_THE_CROWN",
        "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLUTIONARY_YEARS"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_CONSTITUTIONAL_CRISIS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PEOPLE_S_RISING",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PEOPLE_S_REVOLUTION",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SPRING_OF_NATIONS"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_REFORM_MOVEMENT",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_THE_CROWN",
        "LOC_DEMOGRAPHICS_CRISIS_THE_NATIONAL_RISING",
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_REVOLUTIONS"
      ]
    ]
  },
  EXPLORATION_CRISIS_RELIGION: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_SCHISM",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACRED_SCHISM",
      "LOC_DEMOGRAPHICS_CRISIS_THE_TEMPLE_SCHISM",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PROVINCIAL_SCHISM",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REFORMATION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_COUNTER_REFORMATION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REFORMATION_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WARS_OF_RELIGION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_HERESIES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_PROPHETS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RELIGIOUS_UPHEAVAL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_FAITH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_ORTHODOXY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SACRED_WARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WAR_OF_THE_FAITHFUL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WAR_OF_THE_PROPHETS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_ICONOCLAST_CRISIS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_TEMPLE_CRISIS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PILGRIM_WARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_NORTHERN_REFORMATION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_EASTERN_REFORMATION",
      "LOC_DEMOGRAPHICS_CRISIS_THE_HERESY_OF_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_HERESY_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_HERESY_OF_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_HERESY_OF_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_HERESY_OF_THE_HEARTLAND"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_FAITH",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SACRED_SCHISM",
        "LOC_DEMOGRAPHICS_CRISIS_THE_WARS_OF_RELIGION",
        "LOC_DEMOGRAPHICS_CRISIS_THE_REFORMATION"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_ICONOCLAST_CRISIS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_HERESIES",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PILGRIM_WARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_COUNTER_REFORMATION"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_TEMPLE_CRISIS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_WAR_OF_THE_PROPHETS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_SCHISM",
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_PROPHETS"
      ]
    ]
  },
  EXPLORATION_CRISIS_PLAGUE: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_BLACK_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PESTILENCE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_MORTALITY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_FEVER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PERISHING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_PESTILENCE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_MORTALITY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SWEATING_SICKNESS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WASTING_PLAGUE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_YEARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_DYING_TIME",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ASHES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SUMMER_PLAGUE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_WINTER_SICKNESS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SILENT_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_BLACK_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_RED_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREY_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_ASHEN_DEATH",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_FRONTIER",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_PROVINCES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_STEPPE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_COAST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_HEARTLAND"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_SUMMER_PLAGUE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_YEARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_BLACK_DEATH",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_MORTALITY"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_PLAGUE_OF_THE_COAST",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PESTILENCE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_PERISHING",
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ASHES"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_SWEATING_SICKNESS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_WASTING_PLAGUE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_PESTILENCE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_DYING_TIME"
      ]
    ]
  }
};

/** @type {Record<string, { names: string[], arcs: string[][] }>} */
const CRISIS_FALLBACK_BY_AGE = {
  AGE_ANTIQUITY: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_UPHEAVAL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_UNREST",
      "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_TROUBLES",
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_EMPIRE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ANARCHY",
      "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_TURMOIL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_FRACTURING",
      "LOC_DEMOGRAPHICS_CRISIS_THE_SUNDERING"
    ],
    // Escalating 4-beat progressions (one beat per stage) so a crisis with no
    // probed event type can STILL get per-stage names, not only a single name.
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_UNREST",
        "LOC_DEMOGRAPHICS_CRISIS_THE_TIME_OF_TROUBLES",
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_ANARCHY",
        "LOC_DEMOGRAPHICS_CRISIS_THE_GREAT_FRACTURING"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_UPHEAVAL",
        "LOC_DEMOGRAPHICS_CRISIS_THE_YEARS_OF_TURMOIL",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_EMPIRE",
        "LOC_DEMOGRAPHICS_CRISIS_THE_SUNDERING"
      ]
    ]
  },
  AGE_EXPLORATION: {
    names: [
      "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_EMPIRE",
      "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_UPHEAVAL",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLUTIONARY_YEARS",
      "LOC_DEMOGRAPHICS_CRISIS_THE_REFORM_CRISIS"
    ],
    arcs: [
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_REFORM_CRISIS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_UPHEAVAL",
        "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLUTIONARY_YEARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_EMPIRE"
      ],
      [
        "LOC_DEMOGRAPHICS_CRISIS_THE_AGE_OF_UPHEAVAL",
        "LOC_DEMOGRAPHICS_CRISIS_THE_REFORM_CRISIS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_REVOLUTIONARY_YEARS",
        "LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS_OF_EMPIRE"
      ]
    ]
  }
};

/**
 * FNV-1a-ish 32-bit string hash, used to seed deterministic crisis-name picks.
 * @param {string} s Source string.
 * @returns {number} An unsigned 32-bit hash.
 */
function hashString(s) {
  let h = 2166136261 >>> 0; // FNV-1a-ish
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

/**
 * Pick an array element by seed modulo length.
 * @template T
 * @param {T[]} arr Source array.
 * @param {number} seed Seed value.
 * @returns {T} The selected element.
 */
function pickSeeded(arr, seed) {
  return arr[seed % arr.length];
}

/**
 * Read the game's start seed from the engine `Configuration`, defensively.
 * @returns {string} The seed string, or "" when unavailable.
 */
export function getGameSeed() {
  try {
    if (typeof Configuration !== "undefined" && typeof Configuration.getGame === "function") {
      const g = Configuration.getGame();
      const s = g && (g.startSeed ?? g.gameSeed ?? g.mapSeed);
      if (s !== undefined && s !== null) return String(s);
    }
  } catch (_) {
    // Configuration.getGame may be absent or throw; fall back to an empty seed string.
  }
  return "";
}

/**
 * Resolve the `{ names, arcs }` LOC-key entry for a crisis sample, tolerating
 * the legacy flat-array shape. Entries hold `LOC_DEMOGRAPHICS_CRISIS_*` tags.
 * @param {Snapshot|*} sample The crisis sample.
 * @returns {{ names: string[], arcs: string[][] }} The resolved key pools.
 */
function resolveCrisisEntry(sample) {
  const type = sample && sample.crisisEventType;
  const entry = (type && CRISIS_NAME_TEMPLATES[type]) ||
    CRISIS_FALLBACK_BY_AGE[sample && sample.age] || {
      names: ["LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS"],
      arcs: []
    };
  // Backward-compat: tolerate the legacy flat-array shape.
  const names = Array.isArray(entry)
    ? entry
    : entry.names || ["LOC_DEMOGRAPHICS_CRISIS_THE_CRISIS"];
  const arcs = Array.isArray(entry) ? [] : entry.arcs || [];
  return { names, arcs };
}

/**
 * Compose a seeded, historian-style crisis name for a sample + stage, resolving
 * the chosen `LOC_DEMOGRAPHICS_CRISIS_*` tag to the active language. The same
 * game (seed) always reads consistently. ({color}/{place}/{regional} variants
 * are now pre-expanded into concrete, individually localized keys, so no
 * post-compose substitution is needed.)
 * @param {Snapshot|*} sample The crisis sample (carries crisisEventType/age).
 * @param {number} stage The 1-based display stage.
 * @param {string} gameSeedStr The game's seed string.
 * @returns {string} The composed, localized crisis name.
 */
export function flavorCrisisName(sample, stage, gameSeedStr) {
  const type = sample && sample.crisisEventType;
  const { names, arcs } = resolveCrisisEntry(sample);
  const seedKey = (type || (sample && sample.age) || "crisis") + "|" + gameSeedStr;
  const seed = hashString(seedKey);
  // Arc vs single-name decision - seeded so each game commits to one mode for
  // the run. ~35% chance of an arc when arcs exist; otherwise pick from the
  // single-name pool. Single-name is the default so the marker reads as one
  // stable event across all four stages most of the time.
  const useArc = arcs.length > 0 && hashString(seedKey + "|arc-choice") % 100 < 35;
  if (useArc) {
    const arc = arcs[seed % arcs.length];
    const idx = Math.max(0, Math.min(arc.length - 1, (stage | 0 || 1) - 1));
    return t(arc[idx]);
  }
  return t(pickSeeded(names, seed));
}
